version: "3.8"

services:
  postgres:
    image: postgres:15.0
    container_name: booking_postgres
    restart: unless-stopped
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  book-me:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

#  zipkin:
#    image: 'openzipkin/zipkin:latest'
#    ports:
#      - '9411'

volumes:
  postgres-data:

