# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  template: # Template contains the blueprint for pods
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
        - name: booking-db
          image: postgres:16.1
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: postgres-data # matches volumeMounts name above
          persistentVolumeClaim:
            claimName: booking-pvc # references the PVC in 'postgres-storage.yaml'
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: booking-db-service
  labels:
    app: booking-db
    tier: database
spec:
  type: ClusterIP # Only expose the db inside the cluster
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: booking-db  # Matches Deployment's label